#%RAML 1.0
title: New Fantastic API
version: v1
baseUri: http://localhost
types:
  BlobRecord:
    type: object
    properties:
      id: number
      title: string
      summary: string
      deleted: number
      live: number
  Document:
    type: object
    properties:
      fixme: string
  Comment:
    type: object
    properties:
      fixme: string
  DataStream:
    type: object
    properties:
      fixme: string
  Interaction:
    type: object
    properties:
      fixme: string
  LockStatus:
    type: object
    properties:
      locked: boolean
  Audit:
    type: object
    properties:
      data: string # base64 encoded data


/blobrecords:
  get:
    queryParameters:
      tag:
        type: string
      page:
        type: integer
      items:
        type: integer
      startDate:
        type: datetime
      endDate:
        type: datetime
      imageWidth:
        type: integer
      imageHeight:
        type: integer
      priority:
        type: integer
      notRequired:
        type: string[]
    responses:
      200:
        body:
          application/json:
            type: BlobRecord[]
  post:
    body:
      application/json:
        type: BlobRecord
  /{id}:
    delete:
    put:
      body:
        application/json:
          type: BlobRecord
    get:
      queryParameters:
        startDate:
          type: datetime
        endDate:
          type: datetime
        showPrivate:
          type: boolean
      responses:
        200:
          body:
            application/json:
              type: BlobRecord
    /interactions:
      get:
        queryParameters:
          page:
            type: integer
          items:
            type: integer
          orderBy:
            type: string
          action:
            type: string
          search:
            type: string
          xmlDataFilters:
            type: string
        responses:
          200:
            body:
              application/json:
                type: Interaction[]
    /togglelock:
      get:
        responses:
          200:
            body:
              application/json:
                type: LockStatus
      put:
        body:
          application/json:
            type: LockStatus
    /audit:
      get:
        queryParameters:
          historyDays:
            type: integer
        responses:
          200:
            body:
              application/json:
                type: Audit

/datastreams:
  get:
    queryParameters:
      imageWidth:
        type: integer
      imageHeight:
        type: integer
    responses:
      200:
        body:
          application/json:
            type: DataStream[]
  post:
    body:
      application/json:
        type: DataStream
  /{id}:
    delete:
    get:
      queryParameters:
        imageWidth:
          type: integer
        imageHeight:
          type: integer
        disableInheritance:
          type: boolean
      responses:
        200:
          body:
            application/json:
              type: DataStream
    put:
      body:
        application/json:
          type: DataStream
